config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  get '/users', to: 'users#index'
  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
   user_params = params.require(:user).permit(:email, :password)
   # confirm that email/password combination is correct
   @user = User.confirm(user_params)
   if @user
     login(@user)
     flash[:notice] = "Successfully logged in."
     redirect_to @user
   else
     flash[:error] = "Incorrect email or password."
     redirect_to login_path
   end
 end

 def destroy
     session[:user_id] = nil
     flash[:notice] = "Successfully logged out."
     redirect_to root_path
   end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end


  def create
   @user = User.create(user_params)
   login(@user) # <-- log the user in
   redirect_to @user # <-- go to show
 end

  def show
    @user = User.find_by_id(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
  session[:user_id] = user.id
  @current_user = user
end

def current_user
  @current_user ||= User.find_by_id(session[:user_id])
end

def login(user)
  session[:user_id] = user.id
  @current_user = user
end

def logout
  @current_user = session[:user_id] = nil
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul>
      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Create Account", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>

      <% flash.each do |name, msg| %>
    <p>
      <small> <%= name.capitalize %>: <%= msg %> </small>
    </p>
  <% end %>
    </ul>

  <%= yield %>
  <!-- ... -->
  </body>
</html>

app/views/users/index.html.erb
<h1>Welcome to Users Index.</h1>

<div>
There are currently <%= @users.length %> user(s) signed up!
</div>

app/views/users/new.html.erb
Sign Up

<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div>
  Welcome, <%= @user.first_name %>!
</div>